---
# tasks file for puppet_removal

- name: kill running puppet services and remove the service from startup
  service:
    name: "{{ puppet_distro_service_name }}"
    state: stopped
    enabled: no
