---
# tasks file for roles/cifs_creds

- name: generate cifs_creds file
  template:
    src: templates/cifs_creds.j2
    dest: "{{ item.path }}"
    mode: 0400
    owner: root
    group: root
  no_log: true
  loop: {{ cifs_creds }}


- name: ensure cifs-utils is installed
  package:
    name: cifs-utils
    state: latest
