---
# tasks file for roles/cifs_creds

- name: generate cifs_creds file
  template:
    src: templates/cifs_creds.j2
    dest: /root/cifs_creds
    mode: 0400
    owner: root
    group: root
  no_log: true
